Infra 2
Otus-DevOps-2017-11/dvosko_infra pull request #2
Opened 2018-01-04 00:24 UTC by dvosko

HW6

2018-01-09 15:21 UTC, Nklya requested changes
Добрый день.

Денис, условия дз в принципе частично выполнены, а вот деплой некорректный.

Замечания:
1. Деплой некорректный.
2. В ридми нужно было указать команду, которой ты создаешь инстанс.
3. Коммиты в репозиторий у тебя идут не с той почтой, на которую зарегестрирован аккаунт в гитхабе.

Исправить нужно 1 и 2 пункты.
И проверить что команда, которая указана в ридми действительно создает инстанс с приложением.

2018-01-09 15:21 UTC, Nklya commented on README.md
> +# Homework6
В ридми нужно было указать команду, которой ты создаешь инстанс.

2018-01-09 15:21 UTC, Nklya commented on startup_script.sh
> +reddit && bundle install
В баше эта команда не работает. Он не перейдет в папку. В итоге приложение работать не будет. 
Нужно проверять код перед отправкой на проверку.

2018-01-09 15:21 UTC, Nklya commented on deploy.sh
> +reddit && bundle install
В баше эта команда не работает. Он не перейдет в папку. В итоге приложение работать не будет.
Нужно проверять код перед отправкой на проверку.

2018-01-18 10:44 UTC, Nklya approved these changes
Теперь все отлично.

2018-01-18 18:18 UTC, dvosko commented
Спасибо!

2018-01-18 18:18 UTC, merged